#!/usr/bin/env python3
"""Final multi-dataset fold0 gate for GeneSPT-GC-PSP.

This script is independent from the legacy fixed-output GeneSPT stack. It
uses the final strict whole-gene protocol masks generated by
run_final_dataset_audit.py and evaluates:

  - GC-MLP-PCA32-softplus base.
  - GC-MLP descriptor controls.
  - GeneSPT-GC-PSP with the fixed selected PSP mechanism.
  - PSP descriptor / spatial-basis / mean-coefficient controls.

All fitting uses train genes only; val genes select checkpoints, predictable
components and lambda bins; test genes are evaluated once.
"""

from __future__ import annotations

import argparse
import gc
import json
import random
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import scipy.stats as st
import torch
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import Ridge

from run_final_dataset_audit import DATASETS
from run_gene_conditioned_mlp_controls_stabilization import FlexibleMLPDecoder, make_descriptor_control
from run_gc_spatiality_aware_training import compute_spatiality
from run_predictable_spatial_program_folds012 import apply_bin_lambdas, summarize_model
from run_predictable_spatial_program_transfer_fold0 import (
    bin_lambdas_from_val,
    component_stats,
    fit_spatiality_predictor,
    selected_component_prediction,
)
from run_st_spatial_program_decoder_fold0 import Basis, fit_predict_coeff, project_coeff
from run_st_spatial_program_decoder_fold0 import preprocess_train
from run_strict_gene_conditioned_decoder_gate import (
    build_descriptors,
    gene_metrics,
    log1p_cpm,
    make_knn_edges,
    subgroup_indices,
    summarize_gene_df,
)
from run_msr_structural_readout import ssim_components


ROOT = Path("/workspace/GeneSPT")
INFO = ROOT / "results" / "imformation"


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


@dataclass(frozen=True)
class DatasetPaths:
    dataset: str
    data_dir: Path
    mask_dir: Path

    @property
    def st_path(self) -> Path:
        return self.data_dir / "Spatial_count.txt"

    @property
    def scrna_path(self) -> Path:
        return self.data_dir / "scRNA_count.txt"

    @property
    def loc_path(self) -> Path:
        return self.data_dir / "Locations.txt"


def ready_dataset_names(audit_path: Path) -> list[str]:
    df = pd.read_csv(audit_path)
    ready = df[df["ready"].astype(bool)].groupby("dataset")["fold"].nunique()
    return sorted(ready[ready >= 5].index.tolist())


def dataset_paths(dataset: str, mask_root: Path) -> DatasetPaths:
    spec_by_name = {s.name: s for s in DATASETS}
    if dataset not in spec_by_name:
        raise KeyError(f"Unknown dataset: {dataset}")
    spec = spec_by_name[dataset]
    if spec.data_dir is None:
        raise ValueError(f"Dataset {dataset} has no processed data directory.")
    return DatasetPaths(dataset=dataset, data_dir=ROOT / "data" / spec.data_dir, mask_dir=mask_root / dataset)


def read_st(path: Path) -> tuple[np.ndarray, list[str]]:
    df = pd.read_csv(path, sep="\t", dtype=np.float32)
    if df.isna().to_numpy().any():
        df = df.fillna(0.0)
    return df.to_numpy(dtype=np.float32), list(map(str, df.columns))


def read_coords(path: Path) -> np.ndarray:
    df = pd.read_csv(path, sep="\t")
    df = df.apply(pd.to_numeric, errors="coerce")
    df = df.dropna(axis=1, how="all").dropna(axis=0, how="any")
    arr = df.to_numpy(dtype=np.float32)
    if arr.shape[1] > 2:
        arr = arr[:, :2]
    return arr


def read_scrna_aligned(path: Path, st_genes: list[str]) -> tuple[np.ndarray, str, bool]:
    header = pd.read_csv(path, sep="\t", nrows=0).columns.tolist()
    st_set = set(st_genes)
    col_genes = list(map(str, header[1:]))
    if st_set.issubset(set(col_genes)):
        dtype_map = {c: np.float32 for c in header[1:]}
        df = pd.read_csv(path, sep="\t", index_col=0, dtype=dtype_map)
        if df.isna().to_numpy().any():
            df = df.fillna(0.0)
        aligned = df.loc[:, st_genes].to_numpy(dtype=np.float32)
        return aligned, "cells_x_genes", col_genes == st_genes

    # Gene x cell files can be extremely large. Stream rows and parse only the
    # ST genes needed for this strict split instead of reading the full matrix.
    found: dict[str, np.ndarray] = {}
    first_seen: list[str] = []
    with path.open("r", encoding="utf-8", errors="replace") as f:
        next(f, None)
        for line in f:
            if "\t" not in line:
                continue
            gene, rest = line.rstrip("\n").split("\t", 1)
            if len(first_seen) < len(st_genes):
                first_seen.append(gene)
            if gene in st_set:
                found[gene] = np.fromstring(rest, sep="\t", dtype=np.float32)
                if len(found) == len(st_set):
                    break
    if st_set.issubset(found.keys()):
        aligned = np.vstack([found[g] for g in st_genes]).T.astype(np.float32)
        return aligned, "genes_x_cells", first_seen == st_genes
    missing = sorted(st_set - set(col_genes) - set(found.keys()))
    raise ValueError(f"scRNA genes do not cover ST genes; first missing: {missing[:5]}")


def load_masks(mask_dir: Path, fold: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    return (
        np.load(mask_dir / f"fold{fold}_train_gene_idx.npy").astype(np.int64),
        np.load(mask_dir / f"fold{fold}_val_gene_idx.npy").astype(np.int64),
        np.load(mask_dir / f"fold{fold}_test_gene_idx.npy").astype(np.int64),
    )


def train_gc_mlp(
    X: np.ndarray,
    desc_np: np.ndarray,
    train_idx: np.ndarray,
    val_idx: np.ndarray,
    test_idx: np.ndarray,
    device: torch.device,
    steps: int,
    batch_size: int,
    eval_every: int,
    lr: float,
    seed: int,
) -> tuple[dict[str, np.ndarray], pd.DataFrame, float]:
    """Train the canonical softplus GC-MLP and predict val/test only."""
    set_seed(seed)
    x_input_np = X[:, train_idx].astype(np.float32)
    x_input = torch.tensor(x_input_np, device=device)
    y_full = torch.tensor(X, device=device)
    desc = torch.tensor(desc_np.astype(np.float32), device=device)
    train_idx_t = torch.tensor(train_idx, dtype=torch.long, device=device)
    val_idx_t = torch.tensor(val_idx, dtype=torch.long, device=device)
    model = FlexibleMLPDecoder(
        input_dim=x_input_np.shape[1],
        desc_dim=desc_np.shape[1],
        output_mode="softplus",
    ).to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    best_score = -np.inf
    best_state = None
    hist = []
    genes = [str(i) for i in range(X.shape[1])]
    for step in range(1, steps + 1):
        spot_idx = torch.randint(0, X.shape[0], (batch_size,), device=device)
        gene_pos = torch.randint(0, len(train_idx), (batch_size,), device=device)
        gene_idx = train_idx_t[gene_pos]
        pred = model.forward_pairs(x_input, spot_idx, desc[gene_idx])
        target = y_full[spot_idx, gene_idx]
        loss = torch.mean((pred - target) ** 2)
        opt.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        opt.step()
        if step % eval_every == 0 or step == steps:
            with torch.no_grad():
                pred_val = model.predict_matrix(x_input, desc[val_idx_t], chunk=128).detach().cpu().numpy()
            X_pred_val = np.zeros_like(X, dtype=np.float32)
            X_pred_val[:, val_idx] = pred_val
            val_summary = summarize_gene_df(gene_metrics(X, X_pred_val, val_idx, genes))
            score = (
                np.nan_to_num(val_summary["SPCC"], nan=-1.0)
                - 0.05 * np.nan_to_num(val_summary["RMSE"], nan=10.0)
                - 0.05 * np.nan_to_num(val_summary["JS"], nan=10.0, posinf=10.0)
            )
            hist.append(
                {
                    "step": step,
                    "loss": float(loss.detach().cpu()),
                    **{f"val_{k}": v for k, v in val_summary.items()},
                    "score": float(score),
                }
            )
            if score > best_score:
                best_score = float(score)
                best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
    if best_state is not None:
        model.load_state_dict(best_state)
    with torch.no_grad():
        pred_val = model.predict_matrix(x_input, desc[torch.tensor(val_idx, device=device)], chunk=128).detach().cpu().numpy().astype(np.float32)
        pred_test = model.predict_matrix(x_input, desc[torch.tensor(test_idx, device=device)], chunk=128).detach().cpu().numpy().astype(np.float32)
    del model, opt, x_input, y_full, desc, train_idx_t, val_idx_t
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    return {"val": pred_val, "test": pred_test}, pd.DataFrame(hist), float(best_score)


def load_or_train_gc(
    cache_path: Path,
    X: np.ndarray,
    desc_np: np.ndarray,
    train_idx: np.ndarray,
    val_idx: np.ndarray,
    test_idx: np.ndarray,
    device: torch.device,
    args,
    seed: int,
) -> tuple[dict[str, np.ndarray], pd.DataFrame, str]:
    if cache_path.exists() and args.reuse_cache:
        c = np.load(cache_path)
        return {"val": c["pred_val"], "test": c["pred_test"]}, pd.DataFrame([{"source": "cache", "path": str(cache_path)}]), "cache"
    preds, hist, score = train_gc_mlp(
        X=X,
        desc_np=desc_np,
        train_idx=train_idx,
        val_idx=val_idx,
        test_idx=test_idx,
        device=device,
        steps=args.steps,
        batch_size=args.batch_size,
        eval_every=args.eval_every,
        lr=args.lr,
        seed=seed,
    )
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        cache_path,
        pred_val=preds["val"],
        pred_test=preds["test"],
        train_idx=train_idx,
        val_idx=val_idx,
        test_idx=test_idx,
        best_val_score=score,
    )
    return preds, hist, "trained"


def fit_svd_raw_basis(X_train: np.ndarray, k: int, seed: int) -> Basis:
    Xp, meta = preprocess_train(X_train, "raw")
    k_eff = min(int(k), X_train.shape[0] - 2, X_train.shape[1] - 2)
    if k_eff < 2:
        raise ValueError(f"Cannot fit PSP basis with k_eff={k_eff}")
    svd = TruncatedSVD(n_components=k_eff, random_state=seed + k_eff)
    c_train = svd.fit_transform(Xp.T).astype(np.float32)
    a = svd.components_.T.astype(np.float32)
    return Basis(method="svd", preprocess="raw", k=k_eff, A=a, C_train=c_train, meta=meta)


def finite_target(y: np.ndarray) -> np.ndarray:
    y = np.asarray(y, dtype=np.float32).copy()
    finite = np.isfinite(y)
    if not np.any(finite):
        y[:] = 0.0
        return y
    fill = float(np.nanmedian(y[finite]))
    y[~finite] = fill
    return y


def summarize_base_like(
    model: str,
    X: np.ndarray,
    pred_test: np.ndarray,
    test_idx: np.ndarray,
    low_idx: np.ndarray,
    high_idx: np.ndarray,
    genes: list[str],
    extra: dict,
) -> dict:
    row, _ = summarize_model(model, X, pred_test, test_idx, low_idx, high_idx, genes, extra)
    return row


def summarize_model_with_components(
    model: str,
    X: np.ndarray,
    pred_sub: np.ndarray,
    test_idx: np.ndarray,
    low_idx: np.ndarray,
    high_idx: np.ndarray,
    genes: list[str],
    extra: dict,
) -> tuple[dict, pd.DataFrame]:
    row, gene_df = summarize_model(model, X, pred_sub, test_idx, low_idx, high_idx, genes, extra)
    comp_rows = []
    pos = {int(g): j for j, g in enumerate(test_idx)}
    for g in gene_df["gene_idx"].astype(int).to_numpy():
        j = pos.get(int(g))
        if j is None:
            comp_rows.append((np.nan, np.nan, np.nan))
            continue
        lum, con, stru, _ = ssim_components(X[:, int(g)], pred_sub[:, j])
        comp_rows.append((lum, con, stru))
    if comp_rows:
        comps = np.asarray(comp_rows, dtype=np.float64)
        gene_df = gene_df.copy()
        gene_df["luminance"] = comps[:, 0]
        gene_df["contrast"] = comps[:, 1]
        gene_df["structure"] = comps[:, 2]
        all_mask = gene_df["subgroup"].eq("all") if "subgroup" in gene_df.columns else np.ones(len(gene_df), dtype=bool)
        row["luminance"] = float(np.nanmedian(gene_df.loc[all_mask, "luminance"]))
        row["contrast"] = float(np.nanmedian(gene_df.loc[all_mask, "contrast"]))
        row["structure"] = float(np.nanmedian(gene_df.loc[all_mask, "structure"]))
    else:
        row["luminance"] = np.nan
        row["contrast"] = np.nan
        row["structure"] = np.nan
    return row, gene_df


def run_dataset(dataset: str, args, device: torch.device) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, dict]:
    paths = dataset_paths(dataset, args.mask_root)
    cache_dir = args.cache_dir / dataset / f"fold{args.fold}"
    cache_dir.mkdir(parents=True, exist_ok=True)
    print(f"[fold0 gate] {dataset}: loading data", flush=True)

    X_counts, genes = read_st(paths.st_path)
    X = log1p_cpm(X_counts)
    coords = read_coords(paths.loc_path)
    if coords.shape[0] != X.shape[0]:
        raise ValueError(f"{dataset}: coords rows {coords.shape[0]} != spots {X.shape[0]}")
    train_idx, val_idx, test_idx = load_masks(paths.mask_dir, args.fold)
    X_sc_counts, orientation, exact_order = read_scrna_aligned(paths.scrna_path, genes)
    X_sc = log1p_cpm(X_sc_counts)
    print(
        f"[fold0 gate] {dataset}: spots={X.shape[0]} genes={X.shape[1]} train/val/test={len(train_idx)}/{len(val_idx)}/{len(test_idx)} scRNA={X_sc_counts.shape} orientation={orientation}",
        flush=True,
    )

    desc_cache = cache_dir / "descriptors_pca32_nmf32.npz"
    if desc_cache.exists() and args.reuse_cache:
        dc = np.load(desc_cache)
        desc = {"pca32": dc["pca32"], "nmf32": dc["nmf32"], "pca32_nmf32": dc["pca32_nmf32"]}
    else:
        desc = build_descriptors(X_sc, pca_dims=[32], nmf_dims=[32], seed=args.seed)
        desc["pca32_nmf32"] = np.concatenate([desc["pca32"], desc["nmf32"]], axis=1).astype(np.float32)
        np.savez_compressed(desc_cache, **desc)

    edges = make_knn_edges(coords, k=8)
    low_val_idx, high_val_idx = subgroup_indices(X, val_idx, coords)
    low_test_idx, high_test_idx = subgroup_indices(X, test_idx, coords)
    long_rows: list[dict] = []
    gene_rows: list[pd.DataFrame] = []
    histories: list[pd.DataFrame] = []

    print(f"[fold0 gate] {dataset}: training/loading GC-MLP correct", flush=True)
    base, hist, source = load_or_train_gc(
        cache_dir / "gc_mlp_pca32_softplus_correct.npz",
        X,
        desc["pca32"],
        train_idx,
        val_idx,
        test_idx,
        device,
        args,
        seed=args.seed + 1701 * args.fold,
    )
    hist.insert(0, "dataset", dataset)
    hist["model"] = "gc_mlp_pca32_softplus_correct"
    hist["source"] = source
    histories.append(hist)
    base_val_row = summarize_base_like(
        "gc_mlp_pca32_softplus_correct_val",
        X,
        base["val"],
        val_idx,
        low_val_idx,
        high_val_idx,
        genes,
        {"dataset": dataset, "fold": args.fold, "split": "val", "role": "base", "control": "correct", "source": source},
    )
    base_test_row, base_gene = summarize_model_with_components(
        "gc_mlp_pca32_softplus_correct",
        X,
        base["test"],
        test_idx,
        low_test_idx,
        high_test_idx,
        genes,
        {"dataset": dataset, "fold": args.fold, "split": "test", "role": "base", "control": "correct", "source": source},
    )
    long_rows.append(base_test_row)
    gene_rows.append(base_gene)

    if not args.skip_gc_controls:
        for control in ["shuffled", "random"]:
            print(f"[fold0 gate] {dataset}: training/loading GC-MLP {control} descriptor control", flush=True)
            stable_offset = sum(ord(c) for c in f"{dataset}:{control}")
            D_ctrl, _ = make_descriptor_control(desc["pca32"], control, seed=args.seed + stable_offset)
            ctrl_pred, ctrl_hist, ctrl_source = load_or_train_gc(
                cache_dir / f"gc_mlp_pca32_softplus_{control}.npz",
                X,
                D_ctrl,
                train_idx,
                val_idx,
                test_idx,
                device,
                args,
                seed=args.seed + 5000 + len(control) * 97 + args.fold,
            )
            ctrl_hist.insert(0, "dataset", dataset)
            ctrl_hist["model"] = f"gc_mlp_pca32_softplus_{control}"
            ctrl_hist["source"] = ctrl_source
            histories.append(ctrl_hist)
            row, gene_df = summarize_model_with_components(
                f"gc_mlp_pca32_softplus_{control}_descriptor_control",
                X,
                ctrl_pred["test"],
                test_idx,
                low_test_idx,
                high_test_idx,
                genes,
                {"dataset": dataset, "fold": args.fold, "split": "test", "role": "gc_control", "control": control, "source": ctrl_source},
            )
            long_rows.append(row)
            gene_rows.append(gene_df)

    print(f"[fold0 gate] {dataset}: fitting PSP selected mechanism", flush=True)
    k_eff = int(min(64, max(2, len(train_idx) // 2), max(2, X.shape[0] - 2)))
    basis = fit_svd_raw_basis(X[:, train_idx], k=k_eff, seed=args.seed + args.fold)
    D = desc["pca32_nmf32"]
    X_val_proc, val_meta = preprocess_train(X[:, val_idx], "raw")
    C_val_oracle = project_coeff(basis.A, X_val_proc)
    C_val_pred = fit_predict_coeff("ridge", D[train_idx], basis.C_train, D[val_idx], 10.0, seed=args.seed + args.fold)
    comp_df = component_stats(C_val_pred, C_val_oracle)
    comp_df.insert(0, "dataset", dataset)
    comp_df.insert(1, "fold", args.fold)
    comp_df.insert(2, "method", "svd")
    comp_df.insert(3, "preprocess", "raw")
    comp_df.insert(4, "K", basis.k)
    comp_df.insert(5, "descriptor", "pca32_nmf32")
    comp_df.insert(6, "predictor", "ridge")
    comp_df.insert(7, "alpha", 10.0)
    comp_df["rank_score"] = comp_df["component_spearman"].fillna(-1.0) * np.log1p(comp_df["oracle_coeff_var"].clip(lower=0))
    keep = comp_df.sort_values("rank_score", ascending=False).head(min(32, basis.k))["component"].to_numpy(dtype=np.int64)
    program_val = selected_component_prediction(basis.A, C_val_pred, val_meta, keep)
    train_sp = compute_spatiality(X, train_idx, edges)
    train_moran = finite_target(train_sp["MoranI"].to_numpy(dtype=np.float32))
    pred_sp_val = fit_spatiality_predictor(D[train_idx], train_moran, D[val_idx])
    lambdas, lambda_score, lambda_df = bin_lambdas_from_val(X, base["val"], program_val, val_idx, low_val_idx, high_val_idx, genes, pred_sp_val)
    lambda_df.insert(0, "dataset", dataset)
    lambda_df.insert(1, "fold", args.fold)
    q1, q2 = np.quantile(pred_sp_val, [1 / 3, 2 / 3])

    C_test_pred = fit_predict_coeff("ridge", D[train_idx], basis.C_train, D[test_idx], 10.0, seed=args.seed + 99 + args.fold)
    program_test = selected_component_prediction(basis.A, C_test_pred, basis.meta, keep)
    pred_sp_test = fit_spatiality_predictor(D[train_idx], train_moran, D[test_idx])
    selected_test = apply_bin_lambdas(base["test"], program_test, pred_sp_test, (q1, q2), lambdas)
    selected_meta = {
        "dataset": dataset,
        "fold": args.fold,
        "split": "test",
        "role": "selected",
        "control": "correct",
        "method": "svd",
        "preprocess": "raw",
        "K": basis.k,
        "descriptor": "pca32_nmf32",
        "predictor": "ridge",
        "alpha": 10.0,
        "topK_pred": len(keep),
        "lambda_mode": "predicted_spatiality_bins",
        "lambda_selected": json.dumps(lambdas, sort_keys=True),
        "lambda_val_score": float(lambda_score),
        "component_keep": json.dumps([int(x) for x in keep]),
    }
    selected_row, selected_gene = summarize_model_with_components(
        "genespt_gc_psp_correct",
        X,
        selected_test,
        test_idx,
        low_test_idx,
        high_test_idx,
        genes,
        selected_meta,
    )
    long_rows.append(selected_row)
    gene_rows.append(selected_gene)

    if getattr(args, "save_selected_predictions", False):
        np.savez_compressed(
            cache_dir / "genespt_gc_psp_correct.npz",
            pred_test=selected_test.astype(np.float32),
            base_test=base["test"].astype(np.float32),
            program_test=program_test.astype(np.float32),
            train_idx=train_idx.astype(np.int64),
            val_idx=val_idx.astype(np.int64),
            test_idx=test_idx.astype(np.int64),
            keep_components=np.asarray(keep, dtype=np.int64),
            lambda_low=float(lambdas["low"]),
            lambda_mid=float(lambdas["mid"]),
            lambda_high=float(lambdas["high"]),
            lambda_score=float(lambda_score),
            spatiality_q1=float(q1),
            spatiality_q2=float(q2),
        )

    controls = [
        ("psp_shuffled_descriptor_control", make_descriptor_control(D, "shuffled", seed=args.seed + 1 + args.fold)[0], basis, False),
        ("psp_random_descriptor_control", make_descriptor_control(D, "random", seed=args.seed + 2 + args.fold)[0], basis, False),
    ]
    rng = np.random.default_rng(args.seed + 444 + args.fold)
    A_rand = rng.normal(0, float(np.std(basis.A) + 1e-6), size=basis.A.shape).astype(np.float32)
    rand_basis = Basis("random_basis", "raw", basis.k, A_rand, project_coeff(A_rand, X[:, train_idx]), basis.meta)
    controls.extend(
        [
            ("psp_random_spatial_basis_control", D, rand_basis, False),
            ("psp_mean_coefficient_control", D, basis, True),
        ]
    )
    for name, D_ctrl, b_ctrl, mean_coeff in controls:
        if mean_coeff:
            C_ctrl = np.repeat(b_ctrl.C_train.mean(axis=0, keepdims=True), len(test_idx), axis=0).astype(np.float32)
        else:
            C_ctrl = fit_predict_coeff("ridge", D_ctrl[train_idx], b_ctrl.C_train, D_ctrl[test_idx], 10.0, seed=args.seed + 199 + args.fold)
        prog_ctrl = selected_component_prediction(b_ctrl.A, C_ctrl, b_ctrl.meta, keep)
        pred_ctrl = apply_bin_lambdas(base["test"], prog_ctrl, pred_sp_test, (q1, q2), lambdas)
        row, gene_df = summarize_model_with_components(
            name,
            X,
            pred_ctrl,
            test_idx,
            low_test_idx,
            high_test_idx,
            genes,
            {
                "dataset": dataset,
                "fold": args.fold,
                "split": "test",
                "role": "psp_control",
                "control": name.replace("psp_", "").replace("_control", ""),
                "method": b_ctrl.method,
                "preprocess": "raw",
                "K": b_ctrl.k,
                "descriptor": "pca32_nmf32",
                "predictor": "ridge",
                "alpha": 10.0,
                "topK_pred": len(keep),
                "lambda_mode": "predicted_spatiality_bins",
                "lambda_selected": json.dumps(lambdas, sort_keys=True),
                "component_keep": json.dumps([int(x) for x in keep]),
            },
        )
        long_rows.append(row)
        gene_rows.append(gene_df)

    dataset_df = pd.DataFrame(long_rows)
    base_row = dataset_df[dataset_df["model"].eq("gc_mlp_pca32_softplus_correct")].iloc[0]
    for metric in ["SPCC", "SSIM", "RMSE", "JS", "low_expr_SPCC", "high_spatial_SPCC", "high_spatial_RMSE"]:
        dataset_df[f"delta_{metric}_vs_gc_mlp"] = dataset_df[metric].astype(float) - float(base_row[metric])
    gene_df = pd.concat(gene_rows, ignore_index=True)
    hist_df = pd.concat(histories, ignore_index=True) if histories else pd.DataFrame()
    audit = {
        "dataset": dataset,
        "fold": args.fold,
        "n_spots": X.shape[0],
        "n_genes": X.shape[1],
        "train_genes": len(train_idx),
        "val_genes": len(val_idx),
        "test_genes": len(test_idx),
        "scrna_shape_cells_x_genes": str(tuple(X_sc.shape)),
        "scrna_orientation": orientation,
        "scrna_exact_order": exact_order,
        "psp_k_eff": basis.k,
        "psp_topK": len(keep),
        "lambda_selected": json.dumps(lambdas, sort_keys=True),
        "overlap_train_val": int(len(set(train_idx) & set(val_idx))),
        "overlap_train_test": int(len(set(train_idx) & set(test_idx))),
        "overlap_val_test": int(len(set(val_idx) & set(test_idx))),
    }
    del X_counts, X_sc_counts, X_sc, X, desc, base
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    return dataset_df, gene_df, hist_df, {"audit": audit, "components": comp_df, "lambdas": lambda_df}


def decision_for_dataset(df: pd.DataFrame) -> str:
    base = df[df["model"].eq("gc_mlp_pca32_softplus_correct")].iloc[0]
    selected = df[df["model"].eq("genespt_gc_psp_correct")].iloc[0]
    gc_ctrl = df[df["role"].eq("gc_control")]
    psp_ctrl = df[df["role"].eq("psp_control")]
    descriptor_ok = True
    if not gc_ctrl.empty:
        descriptor_ok = bool(
            float(base["SPCC"]) > float(gc_ctrl["SPCC"].max())
            and float(base["RMSE"]) <= float(gc_ctrl["RMSE"].min()) + 1e-12
        )
    psp_controls_ok = bool(
        selected["SPCC"] > psp_ctrl["SPCC"].max()
        and selected["RMSE"] <= psp_ctrl["RMSE"].min() + 1e-12
        and selected["JS"] <= psp_ctrl["JS"].min() + 1e-12
    )
    psp_maintains = bool(
        selected["delta_SPCC_vs_gc_mlp"] >= -0.001
        and selected["delta_RMSE_vs_gc_mlp"] <= 0.0015
        and selected["delta_JS_vs_gc_mlp"] <= 0.0015
    )
    psp_improves = bool(
        selected["delta_SPCC_vs_gc_mlp"] >= 0.002
        or selected["delta_high_spatial_SPCC_vs_gc_mlp"] >= 0.005
        or (selected["delta_RMSE_vs_gc_mlp"] < -0.001 and selected["delta_SPCC_vs_gc_mlp"] >= -0.001)
        or (selected["delta_JS_vs_gc_mlp"] < -0.001 and selected["delta_SPCC_vs_gc_mlp"] >= -0.001)
    )
    if descriptor_ok and psp_controls_ok and (psp_improves or psp_maintains):
        return "PROMOTE_TO_5FOLD"
    if descriptor_ok and psp_controls_ok:
        return "GC_CONFIRMED_PSP_AUXILIARY"
    if descriptor_ok:
        return "GC_CONFIRMED_PSP_FAILED"
    return "FOLD0_GATE_FAILED"


def write_report(long_df: pd.DataFrame, audit_df: pd.DataFrame, out_path: Path) -> None:
    metrics = ["SPCC", "RMSE", "JS", "SSIM", "luminance", "contrast", "structure", "low_expr_SPCC", "high_spatial_SPCC", "high_spatial_RMSE"]
    fold_summary = long_df[["dataset", "model", "role", "control", *metrics, "delta_SPCC_vs_gc_mlp", "delta_RMSE_vs_gc_mlp", "delta_JS_vs_gc_mlp", "delta_high_spatial_SPCC_vs_gc_mlp"]].copy()
    decisions = []
    for dataset, grp in long_df.groupby("dataset"):
        decisions.append({"dataset": dataset, "decision": decision_for_dataset(grp)})
    dec_df = pd.DataFrame(decisions)
    lines = [
        "# Final Multi-Dataset Fold0 Gate Report",
        "",
        "## Protocol",
        "- Primary model: `GeneSPT-GC-PSP`.",
        "- GC base: `GC-MLP-PCA32-softplus`.",
        "- PSP: SVD raw spatial programs, `K=min(64, train_gene_count//2, n_spots-2)`, descriptor `PCA32+NMF32`, Ridge alpha=10, top predictable components up to 32, lambda by predicted spatiality bins.",
        "- Train genes fit the model and spatial programs. Val genes select checkpoints/components/lambda. Test genes are evaluated once.",
        "",
        "## Dataset Audit",
        audit_df.to_string(index=False),
        "",
        "## Fold0 Decisions",
        dec_df.to_string(index=False),
        "",
        "## Fold0 Metrics",
        fold_summary.to_string(index=False),
        "",
        "## Interpretation Rule",
        "- `PROMOTE_TO_5FOLD`: descriptor signal is clean and PSP improves or maintains GC-MLP while PSP controls fail.",
        "- `GC_CONFIRMED_PSP_AUXILIARY`: descriptor signal is clean, PSP controls fail, but PSP does not clearly improve/maintain the base.",
        "- `GC_CONFIRMED_PSP_FAILED`: GC descriptor signal is present but PSP controls or PSP deltas are insufficient.",
        "- `FOLD0_GATE_FAILED`: descriptor controls are not clean.",
    ]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--datasets", nargs="+", default=None)
    ap.add_argument("--fold", type=int, default=0)
    ap.add_argument("--audit-path", type=Path, default=INFO / "final_dataset_audit_summary.csv")
    ap.add_argument("--mask-root", type=Path, default=INFO / "final_multidataset_masks")
    ap.add_argument("--cache-dir", type=Path, default=INFO / "final_multidataset_cache")
    ap.add_argument("--out-dir", type=Path, default=INFO)
    ap.add_argument("--steps", type=int, default=800)
    ap.add_argument("--batch-size", type=int, default=65536)
    ap.add_argument("--eval-every", type=int, default=100)
    ap.add_argument("--lr", type=float, default=2e-3)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--reuse-cache", action=argparse.BooleanOptionalAction, default=True)
    ap.add_argument("--skip-gc-controls", action=argparse.BooleanOptionalAction, default=False)
    ap.add_argument("--save-selected-predictions", action=argparse.BooleanOptionalAction, default=False)
    args = ap.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    args.cache_dir.mkdir(parents=True, exist_ok=True)

    if args.datasets is None:
        datasets = ready_dataset_names(args.audit_path)
    else:
        datasets = args.datasets
    if not datasets:
        raise RuntimeError("No ready datasets selected.")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[fold0 gate] device={device}; datasets={datasets}", flush=True)

    long_parts = []
    gene_parts = []
    hist_parts = []
    audit_rows = []
    comp_parts = []
    lambda_parts = []
    failures = []
    for dataset in datasets:
        try:
            ds_df, gene_df, hist_df, payload = run_dataset(dataset, args, device)
            long_parts.append(ds_df)
            gene_parts.append(gene_df)
            if not hist_df.empty:
                hist_parts.append(hist_df)
            audit_rows.append(payload["audit"])
            comp_parts.append(payload["components"])
            lambda_parts.append(payload["lambdas"])
            print(ds_df[["dataset", "model", "SPCC", "RMSE", "JS", "SSIM", "high_spatial_SPCC", "delta_SPCC_vs_gc_mlp", "delta_RMSE_vs_gc_mlp", "delta_JS_vs_gc_mlp"]].to_string(index=False), flush=True)
        except Exception as exc:
            failures.append({"dataset": dataset, "error": repr(exc)})
            print(f"[fold0 gate] {dataset}: FAILED {exc!r}", flush=True)
            if not args.reuse_cache:
                raise

    if not long_parts:
        raise RuntimeError(f"No datasets completed. Failures: {failures}")

    long_df = pd.concat(long_parts, ignore_index=True)
    gene_df = pd.concat(gene_parts, ignore_index=True)
    hist_df = pd.concat(hist_parts, ignore_index=True) if hist_parts else pd.DataFrame()
    audit_df = pd.DataFrame(audit_rows)
    comp_df = pd.concat(comp_parts, ignore_index=True) if comp_parts else pd.DataFrame()
    lambda_df = pd.concat(lambda_parts, ignore_index=True) if lambda_parts else pd.DataFrame()

    metrics = ["SPCC", "RMSE", "JS", "SSIM", "low_expr_SPCC", "high_spatial_SPCC", "high_spatial_RMSE"]
    summary = (
        long_df.groupby(["dataset", "model", "role", "control"], as_index=False)[metrics]
        .agg(["mean", "median"])
    )
    summary.columns = ["_".join(c).rstrip("_") for c in summary.columns.to_flat_index()]

    long_df.to_csv(args.out_dir / "final_multidataset_fold0_gate_long.csv", index=False)
    summary.to_csv(args.out_dir / "final_multidataset_fold0_gate_summary.csv", index=False)
    gene_df.to_csv(args.out_dir / "final_multidataset_fold0_gate_gene_level.csv", index=False)
    audit_df.to_csv(args.out_dir / "final_multidataset_fold0_gate_audit.csv", index=False)
    comp_df.to_csv(args.out_dir / "final_multidataset_fold0_gate_component_predictability.csv", index=False)
    lambda_df.to_csv(args.out_dir / "final_multidataset_fold0_gate_lambda_selection.csv", index=False)
    if not hist_df.empty:
        hist_df.to_csv(args.out_dir / "final_multidataset_fold0_gate_training_history.csv", index=False)
    if failures:
        pd.DataFrame(failures).to_csv(args.out_dir / "final_multidataset_fold0_gate_failures.csv", index=False)
    else:
        stale_failures = args.out_dir / "final_multidataset_fold0_gate_failures.csv"
        if stale_failures.exists():
            stale_failures.unlink()
    write_report(long_df, audit_df, args.out_dir / "final_multidataset_fold0_gate_decision.md")
    print(f"Report: {args.out_dir / 'final_multidataset_fold0_gate_decision.md'}", flush=True)


if __name__ == "__main__":
    main()
